services:
  - type: web
    name: smart-astronaut-backend
    env: docker
    plan: free
    region: ohio
    branch: main
    rootDir: smart_backend
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
      - key: CORS_ORIGINS
        value: "https://smart-astronaut.vercel.app,https://smart-astronaut-*.vercel.app"
